# Generated by Django 3.1.5 on 2021-01-13 09:48

from django.db import migrations, models
import gdstorage.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('available_sizes', models.JSONField(blank=True, null=True)),
                ('category', models.JSONField()),
                ('brand', models.CharField(max_length=9999)),
                ('image_0', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['READER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'snm.developer@gmail.com'),)), upload_to='lost-empire/')),
                ('image_1', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['READER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'snm.developer@gmail.com'),)), upload_to='lost-empire/')),
                ('hash_key', models.UUIDField(default=uuid.uuid5, editable=False, unique=True)),
            ],
        ),
    ]
