# Generated by Django 3.1.5 on 2021-01-13 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hash_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
