# Generated by Django 3.1.5 on 2021-01-13 14:15

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0002_auto_20210113_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_0',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='lost-empire/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_1',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='lost-empire/'),
        ),
    ]
