# Generated by Django 3.1.5 on 2021-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0003_auto_20210113_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='card_color',
            field=models.CharField(choices=[('1', 'Black'), ('2', 'White'), ('3', 'Gray')], default='Black', max_length=20),
        ),
    ]
