# Generated by Django 3.1.5 on 2021-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0004_products_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='card_color',
            field=models.CharField(choices=[('1', 'black'), ('2', 'white'), ('3', 'gray')], default='black', max_length=20),
        ),
    ]
