# Generated by Django 3.1.5 on 2021-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0005_auto_20210113_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='card_color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('gray', 'gray')], default='black', max_length=20),
        ),
    ]
