# Generated by Django 3.1.5 on 2021-01-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0006_auto_20210113_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
