# Generated by Django 3.1.5 on 2021-01-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0012_auto_20210114_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available_sizes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
