# Generated by Django 3.1.5 on 2021-01-16 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0015_couponcodes_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='hash_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
