# Generated by Django 3.1.5 on 2021-01-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0017_auto_20210117_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=models.CharField(help_text='The Country the products will be shipped to.', max_length=1600),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paypal_auth',
            field=models.CharField(help_text="PayPal's Authorization ID to capture the funds.", max_length=999),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paypal_order_id',
            field=models.CharField(help_text='PayPal Order ID to get the JSON data from PayPal.', max_length=999),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_cost',
            field=models.FloatField(default=0, help_text='Shipping cost is determined by the countries Continent.'),
        ),
    ]
