# Generated by Django 3.1.5 on 2021-01-18 01:17

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0018_auto_20210117_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_1',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='lost-empire/'),
        ),
    ]
