# Generated by Django 3.1.5 on 2021-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0022_auto_20210120_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_company',
            field=models.CharField(blank=True, help_text='The company that will be shipping the products.', max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracker_id',
            field=models.CharField(blank=True, help_text='The tracker code given by the shipping company.', max_length=1600, null=True),
        ),
    ]
