# Generated by Django 3.1.5 on 2021-01-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0023_auto_20210120_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_per',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
