# Generated by Django 3.1.5 on 2021-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0025_auto_20210121_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('COMPLETED', 'COMPLETED'), ('DENIED', 'DENIED')], default='WAITING', max_length=9),
        ),
    ]
