# Generated by Django 3.1.5 on 2021-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0027_auto_20210121_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_per',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
