# Generated by Django 3.1.5 on 2021-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0028_auto_20210121_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_per',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
