# Generated by Django 3.1.5 on 2021-01-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0029_auto_20210121_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='discount_per',
        ),
    ]
